services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: ${DOCKERHUB_USERNAME:-nguyenit3}/storyvn-backend:latest
    container_name: storyvn-backend
    restart: unless-stopped

    ports:
      - "3000:3000"

    env_file:
      - ./backend/.env

    environment:
      - REDIS_URL=redis://redis:6379

    volumes:
      - backend_uploads:/app/uploads

    depends_on:
      - redis


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: ${DOCKERHUB_USERNAME:-nguyenit3}/storyvn-frontend:latest
    container_name: storyvn-frontend
    restart: unless-stopped

    ports:
      - "5000:5000"

    env_file:
      - ./frontend/.env

    depends_on:
      - backend


  redis:
    image: redis:7-alpine
    container_name: storyvn-redis
    restart: unless-stopped

    ports:
      - "6379:6379"
      
    volumes:
      - redis_data:/data


  nginx:
    image: nginx:alpine
    container_name: storyvn-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"    # <-- Mở thêm cổng HTTPS
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro   # <-- Đưa chứng chỉ vào Nginx
    depends_on:
      - backend
      - frontend


volumes:
  redis_data:
  backend_uploads: