import { API_ROUTES } from "@/config/apiRoutes";

export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: API_ROUTES.AUTH.LOGIN,
    REGISTER: API_ROUTES.AUTH.REGISTER,
    VERIFY_OTP: API_ROUTES.AUTH.VERIFY_OTP,
    REFRESH: API_ROUTES.AUTH.REFRESH,
    ME: API_ROUTES.AUTH.ME,
    LOGOUT: API_ROUTES.AUTH.LOGOUT,
    FORGOT_PASSWORD: API_ROUTES.AUTH.FORGOT_PASSWORD,
    RESET_PASSWORD: API_ROUTES.AUTH.RESET_PASSWORD,
  },
  USERS: {
    PROFILE: API_ROUTES.USERS.PROFILE,
    CHANGE_PASSWORD: API_ROUTES.USERS.CHANGE_PASSWORD,
    IDENTIFIER: API_ROUTES.USERS.BY_ID,
    ADMIN_LIST: API_ROUTES.USERS.ADMIN_LIST,
    ADMIN_STATS: API_ROUTES.USERS.ADMIN_STATS,
    UPDATE_ROLE: API_ROUTES.USERS.UPDATE_ROLE,
    UPDATE_STATUS: API_ROUTES.USERS.UPDATE_STATUS,
  },
  UPLOAD: {
    IMAGE: API_ROUTES.UPLOAD.IMAGE,
  },
  AUTHORS: {
    UPGRADE: API_ROUTES.AUTHORS.UPGRADE,
    ME: API_ROUTES.AUTHORS.ME,
  },
} as const;
