export interface ChapterInfo {
  chapterNum: number;
  title: string;
  updatedAt: string;
}

export interface Story {
  id: string;
  title: string;
  slug: string;
  author: string;
  genres: string[];
  synopsis: string;
  coverImage: string;
  bannerImage?: string;
  coverGradient: string;
  rating: number;
  reviewCount: number;
  views: number;
  chaptersCount: number;
  status: "Đang ra" | "Hoàn thành";
  isHot?: boolean;
  isFeatured?: boolean;
  badge?: "HOT" | "FULL" | "NEW" | "ĐÃ HOÀN";
  latestChapter: ChapterInfo;
  rankDaily?: number;
  rankWeekly?: number;
  rankMonthly?: number;
}

export const GENRES = [
  "Tất cả",
  "Tiên Hiệp",
  "Huyền Huyễn",
  "Kiếm Hiệp",
  "Đô Thị",
  "Dân Quốc",
  "Ngôn Tình",
  "Hệ Thống",
  "Trọng Sinh",
  "Khoa Huyễn",
  "Mạt Thế",
] as const;

export const FEATURED_BANNER_STORIES: Story[] = [
  {
    id: "banner-1",
    title: "Trở Về Niên Đại Mang Theo Hệ Thống Đánh Dấu Làm Giàu",
    slug: "tro-ve-nien-dai-mang-theo-he-thong-danh-dau",
    author: "Nam Phi Huyết Khách",
    genres: ["Trọng Sinh", "Hệ Thống", "Đô Thị"],
    synopsis: "Trọng sinh về thập niên 80 với hệ thống điểm danh nhận thưởng mỗi ngày. Từng bước làm giàu, xây dựng đế chế thương mại từ hai bàn tay trắng.",
    coverImage: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=800&q=80",
    bannerImage: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1200&q=80",
    coverGradient: "from-amber-700 via-orange-600 to-yellow-800",
    rating: 4.9,
    reviewCount: 2840,
    views: 892000,
    chaptersCount: 945,
    status: "Đang ra",
    isHot: true,
    isFeatured: true,
    badge: "HOT",
    latestChapter: {
      chapterNum: 945,
      title: "Chương 945: Mở rộng nhà máy xuất khẩu toàn cầu",
      updatedAt: "5 phút trước",
    },
  },
  {
    id: "banner-2",
    title: "Xuyên Về Dân Quốc: Cô Gái Yêu Kiều Mở Xưởng Kiếm Tiền Trúng Lớn",
    slug: "xuyen-ve-dan-quoc-co-gai-yeu-kieu-mo-xuong",
    author: "Thư Tử Họa Hoa",
    genres: ["Dân Quốc", "Ngôn Tình", "Trọng Sinh"],
    synopsis: "Tiểu thư hiện đại xuyên vào thời dân quốc biến động. Bằng tài năng thiết kế và óc kinh doanh nhạy bén, nàng mở xưởng dệt may chấn động cả Thượng Hải.",
    coverImage: "https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=800&q=80",
    bannerImage: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=1200&q=80",
    coverGradient: "from-rose-800 via-pink-700 to-amber-800",
    rating: 4.9,
    reviewCount: 1980,
    views: 742000,
    chaptersCount: 680,
    status: "Đang ra",
    isHot: true,
    isFeatured: true,
    badge: "HOT",
    latestChapter: {
      chapterNum: 680,
      title: "Chương 680: Dạ tiệc thương hội Thượng Hải",
      updatedAt: "15 phút trước",
    },
  },
  {
    id: "banner-3",
    title: "Ta Có Một Giới Tu Tiên",
    slug: "ta-co-mot-gioi-tu-tien",
    author: "Lục Liên Bất Động",
    genres: ["Tiên Hiệp", "Huyền Huyễn"],
    synopsis: "Vô tình kết nối với một tiểu thế giới tu tiên bí ẩn. Ở địa cầu làm người bình thường, ở dị giới thành Thần Ma chí tôn, hai giới qua lại trường sinh bất tử.",
    coverImage: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=800&q=80",
    bannerImage: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80",
    coverGradient: "from-sky-900 via-indigo-900 to-blue-950",
    rating: 4.8,
    reviewCount: 3120,
    views: 950000,
    chaptersCount: 1420,
    status: "Đang ra",
    isHot: true,
    isFeatured: true,
    badge: "HOT",
    latestChapter: {
      chapterNum: 1420,
      title: "Chương 1420: Tinh Hà Thần Điện giáng thế",
      updatedAt: "28 phút trước",
    },
  },
  {
    id: "banner-4",
    title: "Huyền Giám Tiên Tộc",
    slug: "huyen-giam-tien-toc",
    author: "Thính Nhật",
    genres: ["Tiên Hiệp", "Gia Tộc"],
    synopsis: "Một tấm gương cổ rơi vào tay gia tộc nông phu ven bờ hồ. Qua từng thế hệ gian khổ bồi dưỡng, gia tộc bước lên đỉnh cao tiên triều.",
    coverImage: "https://images.unsplash.com/photo-1514539079130-25950c84af65?auto=format&fit=crop&w=800&q=80",
    bannerImage: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1200&q=80",
    coverGradient: "from-teal-900 via-emerald-800 to-cyan-950",
    rating: 5.0,
    reviewCount: 4620,
    views: 1250000,
    chaptersCount: 1100,
    status: "Đang ra",
    isHot: true,
    isFeatured: true,
    badge: "HOT",
    latestChapter: {
      chapterNum: 1100,
      title: "Chương 1100: Gia chủ trúc cơ, trấn áp tam đại tông",
      updatedAt: "40 phút trước",
    },
  },
  {
    id: "banner-5",
    title: "Vạn Cổ Thần Đế",
    slug: "van-co-than-de",
    author: "Phi Thiên Ngư",
    genres: ["Huyền Huyễn", "Kiếm Hiệp"],
    synopsis: "Tám trăm năm trước, Minh Đế chi tử Trương Nhược Trần bị vị hôn thê ám sát. Tám trăm năm sau trọng sinh, quyết quét sạch chư thần báo thù rửa hận.",
    coverImage: "https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=800&q=80",
    bannerImage: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=1200&q=80",
    coverGradient: "from-amber-900 via-purple-900 to-zinc-950",
    rating: 4.8,
    reviewCount: 3890,
    views: 1480000,
    chaptersCount: 4200,
    status: "Hoàn thành",
    isHot: false,
    badge: "ĐÃ HOÀN",
    latestChapter: {
      chapterNum: 4200,
      title: "Chương 4200: Vĩnh Hằng Bất Hủ (Hết)",
      updatedAt: "1 ngày trước",
    },
  },
];

export const MOCK_STORIES: Story[] = [
  {
    id: "story-1",
    title: "Huyền Giám Tiên Tộc",
    slug: "huyen-giam-tien-toc",
    author: "Thính Nhật",
    genres: ["Tiên Hiệp"],
    synopsis: "Gia tộc tu tiên thực thụ, khắc họa từng thế hệ hy sinh và tranh đấu để giữ vững gia nghiệp giữa thời loạn lạc ma đạo.",
    coverImage: "https://images.unsplash.com/photo-1514539079130-25950c84af65?auto=format&fit=crop&w=400&q=80",
    coverGradient: "from-slate-900 to-cyan-900",
    rating: 4.9,
    reviewCount: 3410,
    views: 890000,
    chaptersCount: 1100,
    status: "Đang ra",
    isHot: true,
    badge: "HOT",
    latestChapter: {
      chapterNum: 1100,
      title: "Chương 1100: Đại phong khởi vân",
      updatedAt: "10 phút trước",
    },
  },
  {
    id: "story-2",
    title: "Mẹ Kế Của Đại Phản Diện",
    slug: "me-ke-cua-dai-phan-dien",
    author: "Bạch Giới Tử",
    genres: ["Ngôn Tình", "Trọng Sinh"],
    synopsis: "Xuyên thành mẹ kế độc ác của trùm phản diện tương lai. Nàng quyết tâm nuôi dạy bảo bối thành người tốt, ai ngờ cha đứa bé lại say đắm nàng.",
    coverImage: "https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=400&q=80",
    coverGradient: "from-rose-900 to-amber-900",
    rating: 4.8,
    reviewCount: 2200,
    views: 640000,
    chaptersCount: 380,
    status: "Hoàn thành",
    badge: "ĐÃ HOÀN",
    latestChapter: {
      chapterNum: 380,
      title: "Chương 380: Hạnh phúc trọn vẹn (Hết)",
      updatedAt: "2 ngày trước",
    },
  },
  {
    id: "story-3",
    title: "Vớt Thi",
    slug: "vot-thi",
    author: "Thần Đạo Sinh",
    genres: ["Huyền Huyễn", "Dị Năng"],
    synopsis: "Nghề vớt xác trên dòng Hoàng Hà nghìn năm bí ẩn. Một câu chuyện kỳ bí về âm dương nhân quả và những bí mật chìm dưới đáy sông.",
    coverImage: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=400&q=80",
    coverGradient: "from-red-950 to-neutral-900",
    rating: 4.9,
    reviewCount: 1850,
    views: 520000,
    chaptersCount: 520,
    status: "Hoàn thành",
    badge: "ĐÃ HOÀN",
    latestChapter: {
      chapterNum: 520,
      title: "Chương 520: Đoạn tuyệt âm dương (Hết)",
      updatedAt: "3 ngày trước",
    },
  },
  {
    id: "story-4",
    title: "Không Có Tiền Tu Tiên Cái Gì?",
    slug: "khong-co-tien-tu-tien-cai-gi",
    author: "Mao Lạp",
    genres: ["Tiên Hiệp", "Hài Hước"],
    synopsis: "Tu tiên cũng cần vốn! Linh thạch không đủ thì lấy đâu ra đan dược? Thiếu niên nghèo khổ bước chân vào giới tài chính tiên đạo, thành tỷ phú tu chân.",
    coverImage: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=400&q=80",
    coverGradient: "from-emerald-900 to-teal-950",
    rating: 4.7,
    reviewCount: 1420,
    views: 430000,
    chaptersCount: 720,
    status: "Đang ra",
    isHot: true,
    badge: "HOT",
    latestChapter: {
      chapterNum: 720,
      title: "Chương 720: Thu mua tông môn đối thủ",
      updatedAt: "35 phút trước",
    },
  },
  {
    id: "story-5",
    title: "Vạn Cổ Thần Đế",
    slug: "van-co-than-de-grid",
    author: "Phi Thiên Ngư",
    genres: ["Huyền Huyễn"],
    synopsis: "Trương Nhược Trần thức tỉnh thần huyết, nắm giữ thời gian và không gian, một đường quét ngang chư thiên thần ma.",
    coverImage: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=400&q=80",
    coverGradient: "from-indigo-950 to-blue-900",
    rating: 4.8,
    reviewCount: 4200,
    views: 1480000,
    chaptersCount: 4200,
    status: "Hoàn thành",
    badge: "ĐÃ HOÀN",
    latestChapter: {
      chapterNum: 4200,
      title: "Chương 4200: Vĩnh Hằng Chi Cảnh (Hết)",
      updatedAt: "1 ngày trước",
    },
  },
  {
    id: "story-6",
    title: "Trở Về Niên Đại: Đánh Dấu Làm Giàu",
    slug: "tro-ve-nien-dai-grid",
    author: "Nam Phi Huyết Khách",
    genres: ["Trọng Sinh", "Đô Thị"],
    synopsis: "Hệ thống điểm danh niên đại 80 mang lại vô vàn lương thực, vàng bạc và công nghệ giúp gia đình thoát nghèo vươn lên thịnh vượng.",
    coverImage: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=400&q=80",
    coverGradient: "from-amber-800 to-yellow-900",
    rating: 4.9,
    reviewCount: 2840,
    views: 892000,
    chaptersCount: 945,
    status: "Đang ra",
    isHot: true,
    badge: "HOT",
    latestChapter: {
      chapterNum: 945,
      title: "Chương 945: Tăng tốc đầu tư nhà đất",
      updatedAt: "5 phút trước",
    },
  },
  {
    id: "story-7",
    title: "Xuyên Về Dân Quốc: Mở Xưởng Trúng Lớn",
    slug: "xuyen-dan-quoc-grid",
    author: "Thư Tử Họa Hoa",
    genres: ["Dân Quốc", "Ngôn Tình"],
    synopsis: "Nữ cường nhân khuấy đảo Thượng Hải phồn hoa, lập thương hiệu thời trang vươn tầm thế giới.",
    coverImage: "https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=400&q=80",
    coverGradient: "from-rose-900 to-orange-950",
    rating: 4.9,
    reviewCount: 1980,
    views: 742000,
    chaptersCount: 680,
    status: "Đang ra",
    isHot: true,
    badge: "HOT",
    latestChapter: {
      chapterNum: 680,
      title: "Chương 680: Đấu giá ngàn lượng vàng",
      updatedAt: "15 phút trước",
    },
  },
  {
    id: "story-8",
    title: "Ta Có Một Giới Tu Tiên",
    slug: "ta-co-gioi-tu-tien-grid",
    author: "Lục Liên Bất Động",
    genres: ["Tiên Hiệp"],
    synopsis: "Tài nguyên một giới cung phụng tu luyện, đột phá cảnh giới như uống nước lã.",
    coverImage: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=400&q=80",
    coverGradient: "from-blue-900 to-slate-900",
    rating: 4.8,
    reviewCount: 3120,
    views: 950000,
    chaptersCount: 1420,
    status: "Đang ra",
    badge: "HOT",
    latestChapter: {
      chapterNum: 1420,
      title: "Chương 1420: Thần điện khai mở",
      updatedAt: "28 phút trước",
    },
  },
  {
    id: "story-9",
    title: "Quỷ Bí Chi Chủ",
    slug: "quy-bi-chi-chu-light",
    author: "Ái Tiềm Thủy Đích Ô Tặc",
    genres: ["Khoa Huyễn", "Dị Năng"],
    synopsis: "Kẻ khờ bước ra từ sương mù xám, mở ra kỷ nguyên Ma Dược và các vị thần cổ đại.",
    coverImage: "https://images.unsplash.com/photo-1514539079130-25950c84af65?auto=format&fit=crop&w=400&q=80",
    coverGradient: "from-zinc-900 to-neutral-950",
    rating: 5.0,
    reviewCount: 5120,
    views: 1890000,
    chaptersCount: 1432,
    status: "Hoàn thành",
    badge: "ĐÃ HOÀN",
    latestChapter: {
      chapterNum: 1432,
      title: "Chương 1432: Giấc mơ ngàn năm (Hết)",
      updatedAt: "4 ngày trước",
    },
  },
  {
    id: "story-10",
    title: "Đại Đạo Tranh Phong",
    slug: "dai-dao-tranh-phong-light",
    author: "Phong Ngự Cửu Thu",
    genres: ["Tiên Hiệp", "Huyền Huyễn"],
    synopsis: "Thiên đạo mênh mông, một kiếm phá vạn pháp chứng đạo đỉnh cao tiên đồ.",
    coverImage: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=400&q=80",
    coverGradient: "from-slate-900 to-blue-950",
    rating: 4.9,
    reviewCount: 2150,
    views: 780000,
    chaptersCount: 1824,
    status: "Đang ra",
    badge: "HOT",
    latestChapter: {
      chapterNum: 1824,
      title: "Chương 1824: Nhất kiếm phá thương khung",
      updatedAt: "50 phút trước",
    },
  },
  {
    id: "story-11",
    title: "Phàm Nhân Tu Tiên",
    slug: "pham-nhan-tu-tien-light",
    author: "Vong Ngữ",
    genres: ["Tiên Hiệp"],
    synopsis: "Kinh điển tiên hiệp chân thực nhất về hành trình của Hàn Lập từ thiếu niên bình phàm tới cự phách tiên giới.",
    coverImage: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=400&q=80",
    coverGradient: "from-emerald-950 to-green-900",
    rating: 5.0,
    reviewCount: 6200,
    views: 2450000,
    chaptersCount: 2450,
    status: "Hoàn thành",
    badge: "ĐÃ HOÀN",
    latestChapter: {
      chapterNum: 2450,
      title: "Chương 2450: Phi thăng chân tiên giới (Hết)",
      updatedAt: "5 ngày trước",
    },
  },
  {
    id: "story-12",
    title: "Toàn Cầu Băng Phong",
    slug: "toan-cau-bang-phong-light",
    author: "Tiêu Dao Khách",
    genres: ["Khoa Huyễn", "Mạt Thế"],
    synopsis: "Băng hà kỷ nguyên, nhiệt độ âm 60 độ. Xây dựng hầm trú ẩn an toàn, tích trữ lương thực sinh tồn đỉnh cao.",
    coverImage: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=400&q=80",
    coverGradient: "from-cyan-950 to-sky-900",
    rating: 4.7,
    reviewCount: 980,
    views: 310000,
    chaptersCount: 410,
    status: "Đang ra",
    badge: "HOT",
    latestChapter: {
      chapterNum: 410,
      title: "Chương 410: Đêm bão tuyết phản công",
      updatedAt: "1 giờ trước",
    },
  },
  {
    id: "story-13",
    title: "Tuyệt Thế Vũ Thần",
    slug: "tuyet-the-vu-than-light",
    author: "Tịnh Vô Ngân",
    genres: ["Kiếm Hiệp"],
    synopsis: "Cửu Tiêu đại lục, võ đạo vi tôn. Lâm Phong thức tỉnh song vũ hồn, đạp bằng chư thiên vạn tộc.",
    coverImage: "https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=400&q=80",
    coverGradient: "from-amber-950 to-orange-900",
    rating: 4.7,
    reviewCount: 1650,
    views: 680000,
    chaptersCount: 2475,
    status: "Hoàn thành",
    badge: "ĐÃ HOÀN",
    latestChapter: {
      chapterNum: 2475,
      title: "Chương 2475: Đại kết cục (Hết)",
      updatedAt: "6 ngày trước",
    },
  },
  {
    id: "story-14",
    title: "Đô Thị Tuyệt Phẩm Y Thần",
    slug: "do-thi-y-than-light",
    author: "Bong Bóng Mùa Hạ",
    genres: ["Đô Thị", "Dị Năng"],
    synopsis: "Hạ sơn cứu thế, châm pháp thần kỳ cải tử hoàn sinh, trở thành đệ nhất thánh y nhân gian.",
    coverImage: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=400&q=80",
    coverGradient: "from-teal-950 to-emerald-900",
    rating: 4.6,
    reviewCount: 840,
    views: 290000,
    chaptersCount: 780,
    status: "Đang ra",
    badge: "HOT",
    latestChapter: {
      chapterNum: 780,
      title: "Chương 780: Danh trấn kinh thành",
      updatedAt: "2 giờ trước",
    },
  },
];
